# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #420516;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NavLine = QtWidgets.QFrame(self.centralwidget)
        self.NavLine.setGeometry(QtCore.QRect(0, 80, 1366, 1))
        self.NavLine.setStyleSheet("color:white;")
        self.NavLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.NavLine.setLineWidth(1)
        self.NavLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.NavLine.setObjectName("NavLine")
        self.IconMain = QtWidgets.QLabel(self.centralwidget)
        self.IconMain.setGeometry(QtCore.QRect(14, 15, 111, 51))
        self.IconMain.setText("")
        self.IconMain.setPixmap(QtGui.QPixmap(":/logos/logos/hanger.png"))
        self.IconMain.setScaledContents(True)
        self.IconMain.setAlignment(QtCore.Qt.AlignCenter)
        self.IconMain.setOpenExternalLinks(False)
        self.IconMain.setObjectName("IconMain")
        self.Heading = QtWidgets.QLabel(self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(140, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("color:rgb(200, 186, 194)")
        self.Heading.setObjectName("Heading")
        self.IconMain2 = QtWidgets.QLabel(self.centralwidget)
        self.IconMain2.setGeometry(QtCore.QRect(150, 100, 271, 161))
        self.IconMain2.setText("")
        self.IconMain2.setPixmap(QtGui.QPixmap(":/logos/logos/hanger.png"))
        self.IconMain2.setScaledContents(True)
        self.IconMain2.setAlignment(QtCore.Qt.AlignCenter)
        self.IconMain2.setOpenExternalLinks(False)
        self.IconMain2.setObjectName("IconMain2")
        self.Heading2 = QtWidgets.QLabel(self.centralwidget)
        self.Heading2.setGeometry(QtCore.QRect(500, 100, 441, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(57)
        font.setBold(True)
        font.setWeight(75)
        self.Heading2.setFont(font)
        self.Heading2.setStyleSheet("color:rgb(200, 186, 194)")
        self.Heading2.setObjectName("Heading2")
        self.LoginButtonSettings = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButtonSettings.setGeometry(QtCore.QRect(380, 580, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.LoginButtonSettings.setFont(font)
        self.LoginButtonSettings.setStyleSheet("background: #C4C4C4;\n"
"border-radius: 10px;\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\\n\n"
"font-size: 24px;\\n\n"
"line-height: 90%;")
        self.LoginButtonSettings.setObjectName("LoginButtonSettings")
        self.IconMainCut = QtWidgets.QPushButton(self.centralwidget)
        self.IconMainCut.setGeometry(QtCore.QRect(1242, 17, 101, 51))
        self.IconMainCut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/logos/qut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconMainCut.setIcon(icon)
        self.IconMainCut.setIconSize(QtCore.QSize(60, 60))
        self.IconMainCut.setObjectName("IconMainCut")
        self.UserNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UserNameLabel.setGeometry(QtCore.QRect(390, 346, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.UserNameLabel.setFont(font)
        self.UserNameLabel.setStyleSheet("color:white;")
        self.UserNameLabel.setObjectName("UserNameLabel")
        self.UserNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UserNameInput.setGeometry(QtCore.QRect(390, 380, 581, 51))
        self.UserNameInput.setStyleSheet("border:2px solid white;\n"
"border-radius:10px;\n"
"color:white;\n"
"")
        self.UserNameInput.setObjectName("UserNameInput")
        self.PasswordNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordNameLabel.setGeometry(QtCore.QRect(390, 460, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.PasswordNameLabel.setFont(font)
        self.PasswordNameLabel.setStyleSheet("color:white;")
        self.PasswordNameLabel.setObjectName("PasswordNameLabel")
        self.PasswordNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordNameInput.setGeometry(QtCore.QRect(390, 500, 581, 51))
        self.PasswordNameInput.setStyleSheet("border:2px solid white;\n"
"border-radius:10px;\n"
"color:white;\n"
"")
        self.PasswordNameInput.setObjectName("PasswordNameInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Heading.setText(_translate("MainWindow", "Dress UP"))
        self.Heading2.setText(_translate("MainWindow", "LOGIN"))
        self.LoginButtonSettings.setText(_translate("MainWindow", "LOGIN"))
        self.UserNameLabel.setText(_translate("MainWindow", "USERNAME"))
        self.UserNameInput.setText(_translate("MainWindow", "please enter your Email registered"))
        self.PasswordNameLabel.setText(_translate("MainWindow", "PASSWORD"))
        self.PasswordNameInput.setText(_translate("MainWindow", "please enter your Password registered"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
